export const sidebarContent8 = (
  <>
    <p>
      You were successful, but notice that with less trades done the surplus
      generated by the market is only £140,000.
    </p>
    <p>
      More concerning is that your share of that surplus is only £10,000 such
      that you must pay £270,000 to secure your credits.
    </p>
    <p>
      Your share of the surplus is small because your bid is only marginally
      better than those of the other buyers you beat to the purchase of the
      credits. If the seller were to trade with those other buyers instead the
      market surplus would not reduce that much.
    </p>
    <p>
      In contrast, the single seller is critical to trades occurring in the
      market. As such they make the largest contribution to the generation of
      market surplus and secure the lion's share of that surplus as a bonus of
      £130,000.
    </p>
  </>
);
